### ISSUE TITLE
making solid braids

### ISSUE THREAD

**Issue by madmaze** [jaredly/blender#1]
Hi Jaredly,

I've been tinkering with your scripts a bit and I'm trying to arrive at a simple solid 3-strand braid. 
I am not very familiar with blender and how you can turn a surface into a full solid.
Was wondering whether you could give some pointers or perhaps even update your scripts to include a "solid" option.

I end up with this after tinkering with your example 1: http://i.imgur.com/2aRE5IK.png

Thanks,

Maze

**Comment by jaredly** [comment]
What do you mean by "solid"? Do you want a cap on the end?
In blender, there's not really the notion of a "solid". There are just surfaces.

**Comment by madmaze** [comment]
Thanks for the quick response! 
I'm looking to 3d print it, so I need makerware or repG to see it as a solid so it doesn't just print the shell. I'm not very familiar with the process coming from blender, usually I use OpenSCAD for this.

**Comment by jaredly** [comment]
ok, great. All you need (I believe) is to set the "fill caps" option of the curve. Then you will have an object which, from the perspective of a 3d printer, is "solid".

![screen shot 2013-10-12 at 9 22 21 am](https://f.cloud.github.com/assets/112170/1320310/1bdf6166-3352-11e3-851b-66d0da63fde5.png)

![screen shot 2013-10-12 at 9 20 24 am](https://f.cloud.github.com/assets/112170/1320309/0a27e470-3352-11e3-9ebf-01d29c612164.png)

**Comment by jaredly** [comment]
Or, if you want a smother cap, you can use a "taper object". I've added an example to the repo, "capped_braid.blend" with both kinds.
![screen shot 2013-10-12 at 9 49 32 am](https://f.cloud.github.com/assets/112170/1320369/3d9a3796-3356-11e3-86ac-890c0dcf568f.png)

**Comment by madmaze** [comment]
Fantastic! Thanks

**Comment by jaredly** [comment]
let me know if you print it - I'd love to see how it turns out.

**Comment by madmaze** [comment]
will do

On Sat, Oct 12, 2013 at 3:43 PM, Jared Forsyth notifications@github.comwrote:

> let me know if you print it - I'd love to see how it turns out.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jaredly/blender/issues/1#issuecomment-26204479
> .

## 

Matthias Lee
IDIES/Johns Hopkins University
Performance @ Rational/IBM

Matthias.A.Lee@gmail.com
MatthiasLee@jhu.edu
(320) 496 6293

To know recursion, you must first know recursion.

**Comment by madmaze** [comment]
Banana for scale: http://imgur.com/a/d5VYK
=)

On Sat, Oct 12, 2013 at 4:17 PM, Matthias Lee matthias.a.lee@gmail.comwrote:

> will do
> 
> On Sat, Oct 12, 2013 at 3:43 PM, Jared Forsyth notifications@github.comwrote:
> 
> > let me know if you print it - I'd love to see how it turns out.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/jaredly/blender/issues/1#issuecomment-26204479
> > .
> 
> ## 
> 
> Matthias Lee
> IDIES/Johns Hopkins University
> Performance @ Rational/IBM
> 
> Matthias.A.Lee@gmail.com
> MatthiasLee@jhu.edu
> (320) 496 6293
> 
> To know recursion, you must first know recursion.

## 

Matthias Lee
IDIES/Johns Hopkins University
Performance @ Rational/IBM

Matthias.A.Lee@gmail.com
MatthiasLee@jhu.edu
(320) 496 6293

To know recursion, you must first know recursion.

**Comment by jaredly** [comment]
awesome!
